export const FETCH_BUDGET = "FETCH_BUDGET";
export const RESET_APP = "RESET_APP";
export const ADD_BUDGET_HISTORY = "ADD_BUDGET_HISTORY";
export const EDIT_BUDGET_HISTORY = "EDIT_BUDGET_HISTORY";
export const DELETE_BUDGET_HISTORY = "DELETE_BUDGET_HISTORY";